// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace CyPatients.Models;

public partial class CyhealthCare_dbContext : DbContext
{
    public CyhealthCare_dbContext(DbContextOptions<CyhealthCare_dbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<MaritalStatus> MaritalStatuses { get; set; }

    public virtual DbSet<MedicalEntity> MedicalEntities { get; set; }

    public virtual DbSet<Nationality> Nationalities { get; set; }

    public virtual DbSet<Patient> Patients { get; set; }

    public virtual DbSet<PatientValidationFlag> PatientValidationFlags { get; set; }

    public virtual DbSet<Title> Titles { get; set; }

    public virtual DbSet<VisitType> VisitTypes { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<MaritalStatus>(entity =>
        {
            entity.HasKey(e => e.MaritalStatusId).HasName("PK__MaritalS__C8B1BA72E71F47AE");

            entity.ToTable("MaritalStatus");

            entity.Property(e => e.ArStatusName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("ar_StatusName");
            entity.Property(e => e.EnStatusName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("en_StatusName");
        });

        modelBuilder.Entity<MedicalEntity>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__MedicalE__3213E83F466694E7");

            entity.ToTable("MedicalEntity");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.ArName)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("ar_name");
            entity.Property(e => e.Code).HasColumnName("code");
            entity.Property(e => e.EnName)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("en_name");
            entity.Property(e => e.IsActive).HasColumnName("isActive");
        });

        modelBuilder.Entity<Nationality>(entity =>
        {
            entity.HasKey(e => e.NationalityId).HasName("PK__National__F628E744A5202F73");

            entity.ToTable("Nationality");

            entity.Property(e => e.ArNationality)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("ar_Nationality");
            entity.Property(e => e.EnNationality)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("en_Nationality");
        });

        modelBuilder.Entity<Patient>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Patient__3214EC07444DD64C");

            entity.ToTable("Patient");

            entity.HasIndex(e => e.PersonalId, "UQ__Patient__283437F2617FDB52").IsUnique();

            entity.Property(e => e.AddressDescription).HasMaxLength(200);
            entity.Property(e => e.City).HasMaxLength(50);
            entity.Property(e => e.Country).HasMaxLength(50);
            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.FirstNameAr).HasMaxLength(50);
            entity.Property(e => e.FirstNameEn).HasMaxLength(50);
            entity.Property(e => e.FourthNameAr).HasMaxLength(50);
            entity.Property(e => e.FourthNameEn).HasMaxLength(50);
            entity.Property(e => e.HowDidYouKnowUsId).HasColumnName("HowDidYouKnowUsID");
            entity.Property(e => e.Mobile).HasMaxLength(11);
            entity.Property(e => e.Mobile2).HasMaxLength(11);
            entity.Property(e => e.NationalityId).HasColumnName("NationalityID");
            entity.Property(e => e.Occupation).HasMaxLength(100);
            entity.Property(e => e.PersonalId)
                .HasMaxLength(14)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.ReferringEntityId).HasColumnName("ReferringEntityID");
            entity.Property(e => e.Region).HasMaxLength(50);
            entity.Property(e => e.SecondNameAr).HasMaxLength(50);
            entity.Property(e => e.SecondNameEn).HasMaxLength(50);
            entity.Property(e => e.ThirdNameAr).HasMaxLength(50);
            entity.Property(e => e.ThirdNameEn).HasMaxLength(50);
            entity.Property(e => e.TitleId).HasColumnName("TitleID");

            entity.HasOne(d => d.Branch).WithMany(p => p.Patients)
                .HasForeignKey(d => d.BranchId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Patient_Branch");

            entity.HasOne(d => d.MaritalStatus).WithMany(p => p.Patients)
                .HasForeignKey(d => d.MaritalStatusId)
                .HasConstraintName("FK_Patient_MaritalStatus");

            entity.HasOne(d => d.Nationality).WithMany(p => p.Patients)
                .HasForeignKey(d => d.NationalityId)
                .HasConstraintName("FK_Patients_Nationality");

            entity.HasOne(d => d.Title).WithMany(p => p.Patients)
                .HasForeignKey(d => d.TitleId)
                .HasConstraintName("FK_Patients_Title");

            entity.HasOne(d => d.VisitType).WithMany(p => p.Patients)
                .HasForeignKey(d => d.VisitTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Patient_VisitType");
        });

        modelBuilder.Entity<PatientValidationFlag>(entity =>
        {
            entity.HasKey(e => new { e.VisitTypeId, e.MedicalEntityId });

            entity.Property(e => e.HowDidYouKnowUsId).HasColumnName("HowDidYouKnowUsID");
            entity.Property(e => e.NationalityId).HasColumnName("NationalityID");
            entity.Property(e => e.TitleId).HasColumnName("TitleID");

            entity.HasOne(d => d.MedicalEntity).WithMany(p => p.PatientValidationFlags)
                .HasForeignKey(d => d.MedicalEntityId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PatientValidationFlags_MedicalEntity");

            entity.HasOne(d => d.VisitType).WithMany(p => p.PatientValidationFlags)
                .HasForeignKey(d => d.VisitTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PatientValidationFlags_VisitType");
        });

        modelBuilder.Entity<Title>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Title__3213E83F1EDF83F5");

            entity.ToTable("Title");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.ArTitle)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("ar_title");
            entity.Property(e => e.EnTitle)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("en_title");
        });

        modelBuilder.Entity<VisitType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__VisitTyp__3213E83F70DBCA6E");

            entity.ToTable("VisitType");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.ArVisitName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("ar_VisitName");
            entity.Property(e => e.Code)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("code");
            entity.Property(e => e.ErVisitName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("er_VisitName");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}