// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CyPatients.Models;

public partial class MaritalStatus
{
    public int MaritalStatusId { get; set; }

    public string ArStatusName { get; set; }

    public string EnStatusName { get; set; }

    public virtual ICollection<Patient> Patients { get; set; } = new List<Patient>();
}