// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CyPatients.Models;

public partial class Nationality
{
    public int NationalityId { get; set; }

    public string ArNationality { get; set; }

    public string EnNationality { get; set; }

    public virtual ICollection<Patient> Patients { get; set; } = new List<Patient>();
}