// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using CyPatients.Service.interfaces;
using Humanizer;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CyPatients.Models;

public partial class Patient : IValidatableObject
{
    public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        var results = new List<ValidationResult>();


        var validationService = validationContext.GetService(typeof(IValidationService)) as IValidationService;

        if (validationService == null) yield break; // If service is not available -> skip validation


            var rules = validationService.getValidatVisit(this.VisitTypeId, this.BranchId)
                // Convert async to sync
                .GetAwaiter()
                .GetResult();

            var validationErrors = validationService.Validat(this, rules);


            foreach (var error in validationErrors)
            {

                yield return new ValidationResult(error);
            }
        
        
    }
}