// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CyPatients.Models;

public partial class Title
{
    public int Id { get; set; }

    public string ArTitle { get; set; }

    public string EnTitle { get; set; }

    public virtual ICollection<Patient> Patients { get; set; } = new List<Patient>();
}