// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CyPatients.Models;

public partial class VisitType
{
    public int Id { get; set; }

    public string Code { get; set; }

    public string ArVisitName { get; set; }

    public string ErVisitName { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<PatientValidationFlag> PatientValidationFlags { get; set; } = new List<PatientValidationFlag>();

    public virtual ICollection<Patient> Patients { get; set; } = new List<Patient>();
}